dist: bionic

jobs:
  include:
    - stage: build_docker
      language: minimal
      services:
        - docker
      install:
        - docker-compose up --build --no-start
      script:
        - docker-compose start
        - HEADERS="$(curl -I -s http://localhost:3000/)"
        - STATUS="$(echo $HEADERS | head -n1)"
        - echo "$HEADERS"
        - if [[ "$STATUS" != *"200 OK"* ]]; then echo "$HEADERS"; exit 1; fi
