language: crystal

crystal:
  - latest

dist: bionic

services:
  - docker

before_install:
  - shards update
  - shards install

install:
  - crystal build --error-on-warnings src/invidious.cr
  - docker-compose build

script:
  - crystal tool format --check
  - crystal spec
